PUT http://localhost:3000/users/profile
Content-Type: application/json

{
  "firstName": "Mario",
  "lastName": "Rossi",
  "bio": "Software Developer",
  "webSiteLink": "https://mariosito.com",
  "profileImagePath": "/uploads/profile_image.jpg",
  "socialLink": ["https://twitter.com/mario", "https://github.com/mariorossi"]
}