INSERT INTO public."AuctionCategories" (name) VALUES
    ('Arredamento'),
    ('Elettronica'),
    ('Abbigliamento'),
    ('Sport'),
    ('Collezionismo'),
    ('Antiquariato'),
    ('Giocattoli'),
    ('Auto'),
    ('Moto'),
    ('Bellezza e Cura Personale'),
    ('Cucina'),
    ('Musica'),
    ('Fai da Te'),
    ('Prodotti per Animali'),
    ('Fitness'),
    ('Tecnologia');